### ISSUE TITLE
Support case-sensitive searches

### ISSUE THREAD

**Issue by kumarrishav** [mark-hahn/find-selection#15]
@mark-hahn What key-binding you suggest for this.?

**Comment by mark-hahn** [comment]
I hate to force keys on people.  Especially four keys at once.  Another feature request is to leave them selected as you go by.  That would be six keys!   But oh well, we have to.

Install my package `search-all-keybindings` and use the ones that conflict the least.  Maybe

- ctrl-alt-f3 and ctrl-alt-shift-f3
- ctrl-f4 and ctrl-shift-f4
- ctrl-4 and ctrl-shift-4
- etc.

**Comment by kumarrishav** [comment]
@mark-hahn Thanks :) will work on it soon. Though i got the code how it's working, can you explain in brief the code flow (control flow) of the package i.e.. basically how it works after installing the package, how activate function got trigger after pressing key etc, what others function do..(like deactivate, serialize)..General idea would be enough. Thanks

**Comment by mark-hahn** [comment]
When installed, the package or a link to the package is in `~/.atom/packages`.  

At load time Atom scans all the package folders in `~/.atom/packages` and looks at `package.json` in each.  If the `package.json` does not have a property called `activationEvents` or `activationCommands` then the package is loaded by a `require` call.  You can study NodeJS to see how requiring NPM modules works.  Then the activation function is called on the loaded package, thus "activating" it.  

This all happens at load time and can be slow, which is why you should always have activation commands if possible.  Run the `time-cop` command to see how long each package uses up at load time.  Some of mine use way too much.

If the package.json did have `activationEvents` or `activationCommands`  then the package is not loaded or activated at load time.  Atom watches for any command listed in the activation commands list, and if one is seen, then the package is quickly loaded and activated before the command is sent to the package.

**Comment by mark-hahn** [comment]
One thing about packages is that once they are installed you can just copy the folder to anywhere else.  You just have to make sure there is a link to it in `~/.atom/packages`.  That can be done by running the command `apm link` in the package folder.  This works even when copying them between machines.

**Comment by kumarrishav** [comment]
Patch #16
